// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDavur_f4idchifg5oTScYNWf29pjarefE',
    appId: '1:812357074947:web:649bc923ad06ef135b0e36',
    messagingSenderId: '812357074947',
    projectId: 'pulmosenseai-e7c5e',
    authDomain: 'pulmosenseai-e7c5e.firebaseapp.com',
    storageBucket: 'pulmosenseai-e7c5e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOWsxG8cbDvSMG_68ZqfPqgwX2wEEp_Ro',
    appId: '1:812357074947:android:ee0baf86de8eca595b0e36',
    messagingSenderId: '812357074947',
    projectId: 'pulmosenseai-e7c5e',
    storageBucket: 'pulmosenseai-e7c5e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD78vOt3CWwvFO2e8Ac__0BZ8kueCVOL5I',
    appId: '1:812357074947:ios:40dafe9abf91cc195b0e36',
    messagingSenderId: '812357074947',
    projectId: 'pulmosenseai-e7c5e',
    storageBucket: 'pulmosenseai-e7c5e.firebasestorage.app',
    iosClientId: '812357074947-r5hp2i6ppr3akgoo9k6db54lo7csb8ml.apps.googleusercontent.com',
    iosBundleId: 'com.example.lungSoundSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD78vOt3CWwvFO2e8Ac__0BZ8kueCVOL5I',
    appId: '1:812357074947:ios:40dafe9abf91cc195b0e36',
    messagingSenderId: '812357074947',
    projectId: 'pulmosenseai-e7c5e',
    storageBucket: 'pulmosenseai-e7c5e.firebasestorage.app',
    iosClientId: '812357074947-r5hp2i6ppr3akgoo9k6db54lo7csb8ml.apps.googleusercontent.com',
    iosBundleId: 'com.example.lungSoundSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDavur_f4idchifg5oTScYNWf29pjarefE',
    appId: '1:812357074947:web:f26024757bc383b25b0e36',
    messagingSenderId: '812357074947',
    projectId: 'pulmosenseai-e7c5e',
    authDomain: 'pulmosenseai-e7c5e.firebaseapp.com',
    storageBucket: 'pulmosenseai-e7c5e.firebasestorage.app',
  );
}
